// build.js — Saint Beloved
// Runs at deploy time on Vercel/Netlify.
// Reads all essays from _essays/, converts markdown to HTML,
// writes them into js/essays.js, and generates rss.xml.

const fs = require('fs');
const path = require('path');

const essaysDir = path.join(__dirname, '_essays');
const outputFile = path.join(__dirname, 'js', 'essays.js');
const rssFile = path.join(__dirname, 'rss.xml');

// Site config
const SITE_URL = 'https://saint-beloved.vercel.app';
const SITE_TITLE = 'Saint Beloved';
const SITE_DESCRIPTION = 'Ἐγὼ εἶπα· θεοί ἐστε';

// Ensure required directories exist
fs.mkdirSync(path.join(__dirname, 'js'), { recursive: true });
fs.mkdirSync(path.join(__dirname, '_essays'), { recursive: true });
fs.mkdirSync(path.join(__dirname, 'images', 'uploads'), { recursive: true });

function markdownToHtml(md) {
  return md
    .split('\n\n')
    .map((block) => {
      block = block.trim();
      if (!block) return '';
      if (block.startsWith('## ')) return `<h2>${block.slice(3)}</h2>`;
      if (block.startsWith('# ')) return `<h2>${block.slice(2)}</h2>`;
      if (block.startsWith('> ')) return `<blockquote>${block.slice(2)}</blockquote>`;
      block = block
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.+?)\*/g, '<em>$1</em>')
        .replace(/_(.+?)_/g, '<em>$1</em>');
      return `<p>${block.replace(/\n/g, '<br />')}</p>`;
    })
    .join('\n');
}

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { data: {}, body: content };
  const frontmatter = match[1];
  const body = match[2].trim();
  const data = {};
  frontmatter.split('\n').forEach((line) => {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) return;
    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    data[key] = value;
  });
  return { data, body };
}

function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

let essays = [];

if (fs.existsSync(essaysDir)) {
  const files = fs.readdirSync(essaysDir).filter((f) => f.endsWith('.md'));
  files.forEach((file, index) => {
    const raw = fs.readFileSync(path.join(essaysDir, file), 'utf-8');
    const { data, body } = parseFrontmatter(raw);
    essays.push({
      id: index + 1,
      title: data.title || 'Untitled',
      date: data.date || new Date().toISOString(),
      excerpt: data.excerpt || '',
      cover: data.cover || '',
      body: markdownToHtml(body),
    });
  });
}

essays.sort((a, b) => new Date(b.date) - new Date(a.date));

const output = `// essays.js — Auto-generated by build.js. Do not edit manually.\nwindow.ESSAYS = ${JSON.stringify(essays, null, 2)};\n`;
fs.writeFileSync(outputFile, output, 'utf-8');
console.log(`✓ Saint Beloved: ${essays.length} essay(s) compiled to js/essays.js`);

const rssItems = essays.map((essay) => {
  const url = `${SITE_URL}/essay.html?id=${essay.id}`;
  const pubDate = new Date(essay.date).toUTCString();
  const description = essay.excerpt
    ? escapeXml(essay.excerpt)
    : 'A new essay from Saint Beloved.';
  return `
    <item>
      <title>${escapeXml(essay.title)}</title>
      <link>${url}</link>
      <guid>${url}</guid>
      <pubDate>${pubDate}</pubDate>
      <description>${description}</description>
    </item>`;
}).join('');

const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>${escapeXml(SITE_TITLE)}</title>
    <link>${SITE_URL}</link>
    <description>${escapeXml(SITE_DESCRIPTION)}</description>
    <language>en</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    ${rssItems}
  </channel>
</rss>`;

fs.writeFileSync(rssFile, rss, 'utf-8');
console.log(`✓ Saint Beloved: RSS feed generated at rss.xml`);
